site_name: Jeonghun Lee (Github)
site_description: Jeonghun Lee's Personal Website Link Page
site_author: Jeonghun Lee
repo_url: https://github.com/JeonghunLee/JeonghunLee.github.io
repo_name: JeonghunLee/JeonghunLee.github.io
 

nav:
  - AboutMe: index.md
  - Technical-Skills: project_technical_skills.md
  - Blog Managenment: project_blogs_management.md   
  - ESP-Series: project_esp_series.md  
  - LoRaWAN: project_lorawan.md   
  - Documentation: project_documentation.md  
  
plugins:
  - search
  - mermaid2
  - offline

# Material theme configuration
# https://squidfunk.github.io/mkdocs-material/
theme:
  name: material
  logo: imgs/logo.jpg
  favicon: imgs/logo.jpg
  language: ko
  analytics: # Google Analytics 설정 (https://analytics.google.com/)  (Might be deprecated, use extra.analytics)
    gtag: G-HPQJTYY4LT  # Google Analytics 추적 ID로 교체  https://www.mkdocs.org/user-guide/choosing-your-theme
                        # Admin > Property Settings > Create > Tracking ID (측정ID)
  # Material for MkDocs (Menu 3 개 섹션)
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - toc.follow
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.tooltips
    - content.code.copy
    - toc.integrate         # 이 줄이 TOC(Table of Contents)를 왼쪽 내비(sidebar)로 통합해줌 

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji     
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JeonghunLee
      name: GitHub

    - icon: fontawesome/solid/blog
      link: https://ahyuo79.blogspot.com
      name: Blog (Korean)

    - icon: fontawesome/brands/medium
      link: https://medium.com/@ahyuo79
      name: Medium (English)

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/JeonghunLee-0911/
      name: LinkedIn

    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/jeonghunlee
      name: Docker Hub
  analytics:   # Google Analytics 설정 (https://analytics.google.com/)
    provider: google
    property: G-HPQJTYY4LT  # Google Analytics 추적 ID로 교체  https://www.mkdocs.org/user-guide/choosing-your-theme
                            # Admin > Property Settings > Create > Tracking ID (측정ID)

copyright: >
  © 2025 Jeonghun Lee.
  All rights reserved.